version: '3.8'

services:
  site:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./OCProject_Lettings/:/usr/src/OCProject_Lettings/
    ports:
      - 8000:8000
    env_file:
      - ./.env