version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools
            pip install -r requirements.txt
            ls -l
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 -m pytest
      - run:
          name: Coverage tests
          command: |
            . venv/bin/activate
            pytest -v --cov=. --cov-report=html
      - store_artifacts:
          path: htmlcov/
          destination: python_app
  container:
    docker:
      - image: cimg/base:2022.09
    environment:
      COMMIT_HASH: <<pipeline.trigger_parameters.github_app.commit_sha>>
        # auth:
        #   username: $DOCKERHUB_USERNAME
        #   password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=$COMMIT_HASH
            docker build -t $DOCKERHUB_USERNAME/orange_county:$TAG .
            # echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/orange_county:$TAG

workflows:
  test_build_and_push:
    jobs:
      - build_and_test
      - container
          requires:
            - build_and_test
