# Generated by Django 3.0 on 2023-12-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20231227_1117'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name="Profile",
                    table="profiles_profile",
                )                
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="Profile",
                ) 
            ],
        ),
    ]
